language: python

dist: xenial

python: 3.7

before_install:
  - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/virusshare-hashes.git
  - git config --global user.email "richiebendall@gmail.com"
  - git config --global user.name "ROS Bot"

script:
  - python generate.py
  - git add -f virushashes.txt && git diff-index --quiet HEAD || git commit -q -m "Update Virus Hashes [skip ci]"

after_success:
  - git push origin HEAD:master

notifications:
  email: false
