language:          python

dist:              xenial

addons:
  apt:
    packages:
      - gzip
    sources:
      - github-git-lfs-xenial

python:            3.7

before_install:
  - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/virusshare-hashes.git
  - git config --global user.email "richiebendall@gmail.com"
  - git config --global user.name "ROS Bot"
  - echo -e "machine github.com\n  login $github_token" > ~/.netrc
  - git lfs pull

script:
  - python generate.py
  - gzip -f -k virushashes.txt
  - git add -f virushashes.txt virushashes.txt.gz urls.json && git diff-index --quiet HEAD || git commit -q -m "Update Virus Hashes [skip ci]"

after_success:
  - git push origin HEAD:master

notifications:
  email:           false
