name: Run generate.py

on:
  push:
    branches: [master]

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install python3-pip
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run script
        run: python3 generate.py
# add line
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: virushashes.txt
          path: virushashes.txt
